//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCEloSystemGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public uint MatchesPerPage {
            get {
                return ((uint)(this["MatchesPerPage"]));
            }
            set {
                this["MatchesPerPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Months_4")]
        public global::SCEloSystemGUI.PlayerDevScope PlayerDevelopmentScope {
            get {
                return ((global::SCEloSystemGUI.PlayerDevScope)(this["PlayerDevelopmentScope"]));
            }
            set {
                this["PlayerDevelopmentScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All_Time")]
        public global::SCEloSystemGUI.DevelopmentInterval RatingDevInterval {
            get {
                return ((global::SCEloSystemGUI.DevelopmentInterval)(this["RatingDevInterval"]));
            }
            set {
                this["RatingDevInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matches")]
        public global::SCEloSystemGUI.ResultsDisplay PlayerResultDisplayTypes {
            get {
                return ((global::SCEloSystemGUI.ResultsDisplay)(this["PlayerResultDisplayTypes"]));
            }
            set {
                this["PlayerResultDisplayTypes"] = value;
            }
        }
    }
}
